name: CI Dev

on:
  push:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: |
          echo "Build"
          # ...

      - name: Run tests
        run: |
          echo "Run tests"
          # ...

      - name: Create PR
        if: success()
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Merge dev to main"
          branch: "dev"
          base: "main"
          title: "Auto merge dev to main"
          body: "This PR was automatically created after successful CI on dev branch."
